id: P009661
initial_creation_type: ocr
created_at: 31/03/2020
last_modified_at: 2021-12-19 20:43:21.945294
source_metadata:
  id: bdr:W00KG02764
  title: གཏེར་ལུང་དགོན་པ་དང་བསེ་ཚང་སྤྲུལ་སྐུ་རིམ་བྱོན།
  author: ''
  volumes:
    a6ea35b38a91440495af45ba7310b238:
      image_group_id: I00KG09984
      title: ''
      volume_number: 1
      total_pages: 340
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
