id: I12281FF1
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-31T21:33:14+00:00'
last_modified: '2022-06-08T12:38:51.045169+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W00KG02764
  title: གཏེར་ལུང་དགོན་པ་དང་བསེ་ཚང་སྤྲུལ་སྐུ་རིམ་བྱོན།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    598B:
      image_group_id: I00KG09984
      title: ''
      total_pages: 340
      order: 1
      base_file: 598B.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
